#!/usr/bin/bash
# Go into the home directory
cd ~

# update things and install nodejs and its essentials
sudo apt update && sudo apt ugrade
curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get install nodejs
sudo apt-get install build-essential

#clone the repo
sudo git clone https://www.github.com/Nick-Lemy/country-guide

#install nvm and node 18
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
source ~/.bashrc
sudo nvm install 18
sudo nvm use 18

#cd into the repo and install the dependencies
cd country-guide
sudo npm install axios
sudo npm install express
sudo npm install dotenv

# create the .env file and put the api key in it
echo 'GEMINI=my_api_key' > .env

# install pm2 and start the server
sudo npm install -g pm2
pm2 start server.js --interpreter $(which node)
pm2 startup systemd

# optional: it will set pm2  to start whenever you login to the server
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u sammy --hp /home/ubuntu
systemctl status pm2-ubuntu

# install nginx
sudo apt install nginx

# create a new config file for the default site
new_config=\
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html
		server_name_;
		add_header X-Served-By \$hostname;
		location / {
			proxy_pass http://localhost:3000;
			proxy_http_version 1.1;
			proxy_set_header Upgrade \$http_upgrade;
			proxy_set_header Connection 'upgrade';
			proxy_set_header Host \$host;
			proxy_cache_bypass \$http_upgrade;
		}
		if (\$request_filename ~ redirect_me){
			rewrite ^ https://th3-gr00t.tk/ permanent;
		}
		error_page 404 /error_404.html;
		location = /error_404.html {
			internal;
		}
}
"
# replace the default config file with the new one by first changing the permissions
sudo chown -R ubuntu:ubuntu /etc/nginx/sites-available/default
echo "$new_config" > /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart
